DROP TABLE IF EXISTS M_GROUP_FUNCTION;

CREATE TABLE M_GROUP_FUNCTION (
    GROUP_ID     VARCHAR(16)  NOT NULL COMMENT 'グループID'
   ,FUNCTION_ID  VARCHAR(16)  NOT NULL COMMENT '機能ID'
   ,INS_DATETIME DATETIME     NOT NULL COMMENT '追加日時'
   ,INS_USER_ID  INTEGER      NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME     NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID  INTEGER      NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER      NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER      NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER      NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(GROUP_ID, FUNCTION_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
