DROP TABLE IF EXISTS {%prefix}M_BELONGING;

CREATE TABLE {%prefix}M_BELONGING (
    GROUP_ID     VARCHAR(16) NOT NULL COMMENT 'グループＩＤ'
   ,USER_ID      VARCHAR(32) NOT NULL COMMENT 'ユーザID'
   ,INS_DATETIME DATETIME    NOT NULL COMMENT '追加日時'
   ,INS_USER_ID  INTEGER     NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME    NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID  INTEGER     NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER     NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER     NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER     NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(GROUP_ID,USER_ID)
   ,INDEX(USER_ID,GROUP_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
