DROP TABLE IF EXISTS {%prefix}M_DOC_PAGE;

CREATE TABLE {%prefix}M_DOC_PAGE (
    DOC_ID           VARCHAR(16)    NOT NULL COMMENT '文書ID'
   ,PAGE_NUM         INTEGER        NOT NULL COMMENT 'ページ番号'
   ,CONTENT          MEDIUMBLOB     NOT NULL COMMENT '内容'
   ,EXCEL_SHEET_NAME VARCHAR(64)    NOT NULL COMMENT 'エクセルシート名'
   ,COMMENT          VARCHAR(1024)  COMMENT 'コメント'
   ,INS_DATETIME     DATETIME       NOT NULL COMMENT '追加日時'
   ,INS_USER_ID      INTEGER        NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME     DATETIME       NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID      INTEGER        NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM          INTEGER        NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION         INTEGER        NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE            INTEGER        NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(DOC_ID,PAGE_NUM)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;

DROP TRIGGER IF EXISTS {%prefix}M_DOC_PAGE_UPDATE_TRIGGER;
DELIMITER $$
CREATE TRIGGER {%prefix}M_DOC_PAGE_UPDATE_TRIGGER AFTER UPDATE ON {%prefix}M_DOC_PAGE FOR EACH ROW
BEGIN
    UPDATE
        {%prefix}M_DOC_PAGE
    SET
        UPD_DATETIME = CURRENT_TIMESTAMP
       ,REVISION = OLD.REVISION + 1
    WHERE
        ROW_NUM = OLD.ROW_NUM
    ;
END
$$
DELIMITER ;
