DROP TABLE IF EXISTS {%prefix}M_FUNCTION;

CREATE TABLE {%prefix}M_FUNCTION (
    FUNCTION_ID  VARCHAR(16) NOT NULL COMMENT '機能ID'
   ,NAME         VARCHAR(64) NOT NULL COMMENT '機能名'
   ,ORDER_NUM    INTEGER     NOT NULL COMMENT '表示順'
   ,INS_DATETIME DATETIME    NOT NULL COMMENT '追加日時'
   ,INS_USER_ID  INTEGER     NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME    NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID  INTEGER     NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER     NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER     NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER     NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(FUNCTION_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;


DROP TRIGGER IF EXISTS {%prefix}M_FUNCTION_UPDATE_TRIGGER;
DELIMITER $$
CREATE TRIGGER {%prefix}M_FUNCTION_UPDATE_TRIGGER AFTER UPDATE ON {%prefix}M_FUNCTION FOR EACH ROW
BEGIN
    UPDATE
        {%prefix}M_FUNCTION
    SET
        UPD_DATETIME = CURRENT_TIMESTAMP
       ,REVISION = OLD.REVISION + 1
    WHERE
        ROW_NUM = OLD.ROW_NUM
    ;
END
$$
DELIMITER ;
