DROP TABLE IF EXISTS {%prefix}M_GROUP;

CREATE TABLE {%prefix}M_GROUP (
    GROUP_ID     CHAR(36)      NOT NULL COMMENT 'グループＩＤ'
   ,NAME         VARCHAR(64)   NOT NULL COMMENT 'グループ名'
   ,ORDER_NUM    INTEGER       NOT NULL COMMENT '表示順'
   ,COMMENT      VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(GROUP_ID)
   ,INDEX(ORDER_NUM)
   ,INDEX(NAME)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
