DROP TABLE IF EXISTS {%prefix}M_REQ_ROOT;

CREATE TABLE {%prefix}M_REQ_ROOT (
    DOC_ID       VARCHAR(16)   NOT NULL COMMENT '文書ID'
   ,GROUP_ID     VARCHAR(16)   NOT NULL COMMENT 'ユーザID'
   ,WF_ROOT_ID   VARCHAR(16)   NOT NULL COMMENT 'ルートID'
   ,COMMENT      VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME DATETIME      NOT NULL COMMENT '追加日時'
   ,INS_USER_ID  INTEGER       NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID  INTEGER       NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(DOC_ID,GROUP_ID)
   ,INDEX(GROUP_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;

DROP TRIGGER IF EXISTS {%prefix}M_REQ_ROOT_UPDATE_TRIGGER;
DELIMITER $$
CREATE TRIGGER {%prefix}M_REQ_ROOT_UPDATE_TRIGGER AFTER UPDATE ON {%prefix}M_REQ_ROOT FOR EACH ROW
BEGIN
    UPDATE
        {%prefix}M_REQ_ROOT
    SET
        UPD_DATETIME = CURRENT_TIMESTAMP
       ,REVISION = OLD.REVISION + 1
    WHERE
        ROW_NUM = OLD.ROW_NUM
    ;
END
$$
DELIMITER ;
