DROP TABLE IF EXISTS {%prefix}M_REQ_ROOT;

CREATE TABLE {%prefix}M_REQ_ROOT (
    DOC_ID       CHAR(36)      NOT NULL COMMENT '文書ID'
   ,GROUP_ID     CHAR(36)      NOT NULL COMMENT 'ユーザID'
   ,WF_ROOT_ID   CHAR(36)      NOT NULL COMMENT 'ルートID'
   ,COMMENT      VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(DOC_ID,GROUP_ID)
   ,INDEX(GROUP_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
