DROP TABLE IF EXISTS M_SEQ;

CREATE TABLE M_SEQ (
    SEQ_ID       VARCHAR(16)   NOT NULL COMMENT '採番ID'
   ,SEQ_NUM      INTEGER       NOT NULL DEFAULT 0 COMMENT '次採番番号'
   ,DIGIT        INTEGER       NOT NULL DEFAULT 16 COMMENT '桁数'
   ,COMMENT      VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME DATETIME      NOT NULL COMMENT '追加日時'
   ,INS_USER_ID  INTEGER       NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID  INTEGER       NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(SEQ_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
