DROP TABLE IF EXISTS {%prefix}M_USER;

CREATE TABLE {%prefix}M_USER (
    ID             INTEGER       NOT NULL AUTO_INCREMENT
   ,USER_ID        VARCHAR(32)   NOT NULL COMMENT 'ユーザID'
   ,PASSWORD       TINYTEXT      NOT NULL COMMENT 'パスワード'
   ,NAME           VARCHAR(64)   NOT NULL COMMENT '氏名'
   ,NAME_KANA      VARCHAR(64)   NOT NULL COMMENT '氏名(カナ)'
   ,COMMENT        TEXT          COMMENT 'コメント'
   ,EMPLOYEE_NUM   VARCHAR(16)   COMMENT '社員番号'
   ,MAIL_ADDRESS   VARCHAR(256)  COMMENT 'メールアドレス'
   ,INS_DATETIME   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID    VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID    VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,REVISION       INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE          INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(ID)
   ,UNIQUE KEY(USER_ID)
)
;
