DROP TABLE IF EXISTS {%prefix}M_WF_ROUTE_STEP;

CREATE TABLE {%prefix}M_WF_ROUTE_STEP (
    WF_ROUTE_ID      CHAR(36)      NOT NULL COMMENT 'ワークフロールートID'
   ,STEP_NUM         INTEGER       NOT NULL COMMENT 'ステップ番号'
   ,APPROVAL_USER_ID VARCHAR(32)   NOT NULL COMMENT '承認ユーザID'
   ,INS_DATETIME     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID      VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID      VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,ROW_NUM          INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION         INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE            INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(WF_ROUTE_ID,STEP_NUM)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
