DROP TABLE IF EXISTS {%prefix}T_FILE;

CREATE TABLE {%prefix}T_FILE (
    FILE_ID      VARCHAR(16)   NOT NULL COMMENT 'ファイルID'
   ,NAME         VARCHAR(128)  NOT NULL COMMENT 'ファイル名'
   ,CONTENT      LONGBLOB      NOT NULL COMMENT 'コンテンツ'
   ,MIME_TYPE    VARCHAR(32)   NOT NULL COMMENT 'MIMEタイプ'
   ,COMMENT      VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME DATETIME      NOT NULL COMMENT '追加日時'
   ,INS_USER_ID  INTEGER       NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID  INTEGER       NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(FILE_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;

DROP TRIGGER IF EXISTS {%prefix}T_FILE_UPDATE_TRIGGER;
DELIMITER $$
CREATE TRIGGER {%prefix}T_FILE_UPDATE_TRIGGER AFTER UPDATE ON {%prefix}T_FILE FOR EACH ROW
BEGIN
    UPDATE
        {%prefix}T_FILE
    SET
        UPD_DATETIME = CURRENT_TIMESTAMP
       ,REVISION = OLD.REVISION + 1
    WHERE
        ROW_NUM = OLD.ROW_NUM
    ;
END
$$
$DELIMITER ;
