DROP TABLE IF EXISTS {%prefix}T_FILE;

CREATE TABLE {%prefix}T_FILE (
    FILE_ID      CHAR(36)      NOT NULL COMMENT 'ファイルID'
   ,NAME         VARCHAR(128)  NOT NULL COMMENT 'ファイル名'
   ,CONTENT      LONGBLOB      NOT NULL COMMENT 'コンテンツ'
   ,MIME_TYPE    VARCHAR(32)   NOT NULL COMMENT 'MIMEタイプ'
   ,COMMENT      VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(FILE_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
