DROP TABLE IF EXISTS {%prefix}T_INVALID_ACCESS;

CREATE TABLE {%prefix}T_INVALID_ACCESS (
    ID               INTEGER      NOT NULL AUTO_INCREMENT
   ,CLIENT_IP        VARCHAR(255) NOT NULL COMMENT 'クライアントIPアドレス'
   ,ACCESS_DATETIME  DATETIME     NOT NULL COMMENT 'アクセス日時'
   ,INS_DATETIME     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID      VARCHAR(32)  NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID      VARCHAR(32)  NOT NULL COMMENT '更新ユーザID'
   ,REVISION         INTEGER      NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE            INTEGER      NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY (ID)
   ,INDEX(CLIENT_IP)
)
;
