DROP TABLE IF EXISTS {%prefix}T_INVALID_ACCESS;

CREATE TABLE {%prefix}T_INVALID_ACCESS (
    ACCESS_ID        INTEGER      NOT NULL AUTO_INCREMENT COMMENT 'アクセスID'
   ,CLIENT_IP        VARCHAR(255) NOT NULL COMMENT 'クライアントIPアドレス'
   ,ACCESS_DATETIME  DATETIME     NOT NULL COMMENT 'アクセス日時'
   ,PRIMARY KEY (ACCESS_ID)
)
;
