DROP TABLE IF EXISTS {%prefix}T_NOTIFICATION;

CREATE TABLE {%prefix}T_NOTIFICATION (
    NOTIFICATION_ID VARCHAR(16)   NOT NULL COMMENT '通知ID'
   ,TARGET_USER_ID  VARCHAR(16)   NOT NULL COMMENT '対象ユーザID'
   ,LEVEL           VARCHAR(1)    NOT NULL COMMENT '通知レベル' /* I:information W:warning A:Alert */
   ,COMMENT         VARCHAR(1024) COMMENT 'コメント'
   ,CONFIRMED       VARCHAR(1)    NOT NULL COMMENT '確認フラグ'
   ,FUNCTION_ID     VARCHAR(16)   COMMENT '機能ID'
   ,INS_DATETIME    DATETIME      NOT NULL COMMENT '追加日時'
   ,INS_USER_ID     INTEGER       NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME    DATETIME      NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID     INTEGER       NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM         INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION        INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE           INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(NOTIFICATION_ID)
   ,INDEX(TARGET_USER_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;

DROP TRIGGER IF EXISTS {%prefix}T_NOTIFICATION_UPDATE_TRIGGER;
DELIMITER $$
CREATE TRIGGER {%prefix}T_NOTIFICATION_UPDATE_TRIGGER AFTER UPDATE ON {%prefix}T_NOTIFICATION FOR EACH ROW
BEGIN
    UPDATE
        {%prefix}T_NOTIFICATION
    SET
        UPD_DATETIME = CURRENT_TIMESTAMP
       ,REVISION = OLD.REVISION + 1
    WHERE
        ROW_NUM = OLD.ROW_NUM
    ;
END
$$
$DELIMITER ;
