DROP TABLE IF EXISTS {%prefix}T_NOTIFICATION;

CREATE TABLE {%prefix}T_NOTIFICATION (
    ID              INTEGER       NOT NULL AUTO_INCREMENT
   ,TARGET_USER_ID  VARCHAR(32)   NOT NULL COMMENT '対象ユーザID'
   ,COMMENT         VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID     VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID     VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,REVISION        INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE           INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(ID)
   ,INDEX(TARGET_USER_ID, INS_DATETIME)
)
;
