DROP TABLE IF EXISTS {%prefix}T_QUESTIONARY_ANSWER;

CREATE TABLE {%prefix}T_QUESTIONARY_ANSWER (
    ID             INTEGER       NOT NULL AUTO_INCREMENT
   ,QUESTIONARY_ID CHAR(36)      NOT NULL
   ,BRANCH         INTEGER       NOT NULL
   ,ANSWER_TEXT    TEXT          NOT NULL
   ,ANSWER_COUNT   INTEGER       NOT NULL DEFAULT 0
   ,INS_DATETIME   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID    VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID    VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,REVISION       INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE          INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(ID)
   ,UNIQUE KEY(QUESTIONARY_ID, BRANCH)
)
;
