DROP TABLE IF EXISTS {%prefix}T_REQ_HISTORY;

CREATE TABLE {%prefix}T_REQ_HISTORY (
    REQ_ID       CHAR(36)      NOT NULL COMMENT '申請ID'
   ,BRANCH       INTEGER       NOT NULL COMMENT '枝番'
   ,USER_ID      VARCHAR(32)   NOT NULL COMMENT 'ユーザID'
   ,OPERATION    VARCHAR(16)   NOT NULL COMMENT '操作(APPLICATION:申請, APPROVAL:承認, DENIAL:否認)'
   ,COMMENT      VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(REQ_ID,BRANCH)
   ,INDEX(USER_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
