DROP TABLE IF EXISTS {%prefix}T_REQ_HEADER;

CREATE TABLE {%prefix}T_REQ_HEADER (
    REQ_ID           CHAR(36)    NOT NULL COMMENT '申請ID'
   ,WF_ID            CHAR(36)    NOT NULL COMMENT 'ワークフローID'
   ,REQ_USER_ID      VARCHAR(32) NOT NULL COMMENT '申請ユーザID'
   ,DOC_ID           CHAR(36)    NOT NULL COMMENT '文書ID'
   ,REQ_STATE        VARCHAR(16) NOT NULL COMMENT '申請状態(EDITING:編集中, APPLYING:申請中, APPROVAL:承認, DENIAL:否認)'
   ,APPROVAL_USER_ID VARCHAR(32) NOT NULL COMMENT '承認ユーザID'
   ,INS_DATETIME     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID      VARCHAR(32) NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID      VARCHAR(32) NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,ROW_NUM          INTEGER     NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION         INTEGER     NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE            INTEGER     NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(REQ_ID)
   ,INDEX(REQ_USER_ID)
   ,INDEX(APPROVAL_USER_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
