DROP TABLE IF EXISTS {%prefix}T_REQ_HISTORY;

CREATE TABLE {%prefix}T_REQ_HISTORY (
    REQ_ID       VARCHAR(16)   NOT NULL COMMENT '申請ID'
   ,BRANCH       INTEGER       NOT NULL COMMENT '枝番'
   ,USER_ID      VARCHAR(32)   NOT NULL COMMENT 'ユーザID'
   ,OPERATION    VARCHAR(16)   NOT NULL COMMENT '操作(APPLICATION:申請, APPROVAL:承認, DENIAL:否認)'
   ,COMMENT      VARCHAR(1024) COMMENT 'コメント'
   ,INS_DATETIME DATETIME      NOT NULL COMMENT '追加日時'
   ,INS_USER_ID  INTEGER       NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID  INTEGER       NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(REQ_ID,BRANCH)
   ,INDEX(USER_ID)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;

DROP TRIGGER IF EXISTS {%prefix}T_REQ_HISTORY_UPDATE_TRIGGER;
DELIMITER $$
CREATE TRIGGER {%prefix}T_REQ_HISTORY_UPDATE_TRIGGER AFTER UPDATE ON {%prefix}T_REQ_HISTORY FOR EACH ROW
BEGIN
    UPDATE
        {%prefix}T_REQ_HISTORY
    SET
        UPD_DATETIME = CURRENT_TIMESTAMP
       ,REVISION = OLD.REVISION + 1
    WHERE
        ROW_NUM = OLD.ROW_NUM
    ;
END
$$
DELIMITER ;
