DROP TABLE IF EXISTS {%prefix}T_REQ_ITEM;

CREATE TABLE {%prefix}T_REQ_ITEM (
    REQ_ID       CHAR(36)      NOT NULL COMMENT '申請ID'
   ,PAGE_NUM     INTEGER       NOT NULL COMMENT 'ページ番号'
   ,ITEM_ID      VARCHAR(32)   NOT NULL COMMENT '項目ID'
   ,MODE         VARCHAR(16)   NOT NULL COMMENT 'モード(CONFIRMED, EDITING)'
   ,INPUT_VALUE  TEXT          NOT NULL COMMENT '入力値'
   ,INS_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時'
   ,INS_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
   ,UPD_USER_ID  VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(REQ_ID,PAGE_NUM,ITEM_ID,MODE)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;
