DROP TABLE IF EXISTS {%prefix}T_REQ_ITEM;

CREATE TABLE {%prefix}T_REQ_ITEM (
    REQ_ID       VARCHAR(16)   NOT NULL COMMENT '申請ID'
   ,PAGE_NUM     INTEGER       NOT NULL COMMENT 'ページ番号'
   ,ITEM_ID      VARCHAR(32)   NOT NULL COMMENT '項目ID'
   ,MODE         VARCHAR(16)   NOT NULL COMMENT 'モード(CONFIRMED, EDITING)'
   ,INPUT_VALUE  TEXT          NOT NULL COMMENT '入力値'
   ,INS_DATETIME DATETIME      NOT NULL COMMENT '追加日時'
   ,INS_USER_ID  INTEGER       NOT NULL COMMENT '追加ユーザID'
   ,UPD_DATETIME DATETIME      NOT NULL COMMENT '更新日時'
   ,UPD_USER_ID  INTEGER       NOT NULL COMMENT '更新ユーザID'
   ,ROW_NUM      INTEGER       NOT NULL AUTO_INCREMENT COMMENT '行番号'
   ,REVISION     INTEGER       NOT NULL DEFAULT 1 COMMENT 'リビジョン'
   ,STATE        INTEGER       NOT NULL DEFAULT 0 COMMENT '状態'
   ,PRIMARY KEY(REQ_ID,PAGE_NUM,ITEM_ID,MODE)
   ,INDEX(ROW_NUM)
   ,UNIQUE KEY(ROW_NUM)
)
;

DROP TRIGGER IF EXISTS {%prefix}T_REQ_ITEM_UPDATE_TRIGGER;
DELIMITER $$
CREATE TRIGGER {%prefix}T_REQ_ITEM_UPDATE_TRIGGER AFTER UPDATE ON {%prefix}T_REQ_ITEM FOR EACH ROW
BEGIN
    UPDATE
        {%prefix}T_REQ_ITEM
    SET
        UPD_DATETIME = CURRENT_TIMESTAMP
       ,REVISION = OLD.REVISION + 1
    WHERE
        ROW_NUM = OLD.ROW_NUM
    ;
END
$$
DELIMITER ;
